const url=require('url');
var webaddress="http://localhost:3000/index.html?name=sree&age=26";
var part=url.parse(webaddress,true);
console.log(part);
console.log(part.host);
console.log(part.pathname);
console.log(part.search);
console.log(part.query); 
console.log(part.query.age);
console.log(part.port);